baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "bleog"
theme = 'beautifulhugo'
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
 # homeTitle = "Leonardo's Blog" # Set a different text for the header on the home page
  subtitle = "Leonardo's Blog"
  mainSections = ["post","posts"]

  favicon = "images/favicon.ico"

  readingTime = true
  hideAuthor = true
  socialShare = true

[[Params.bigimg]]
  src = "images/home.png"
  desc = "CloudNativePG"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Leonardo Cecchi"
  github = "leonardoce"
  twitter = "leonardo_cecchi"
  linkedin = "leonardo-cecchi-54b0a396"

[[menu.main]]
    name = "Me"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
